---
- name: Deployment of Web server 
  hosts: webserver
  become: yes

  vars:
    web_pkg: nginx
    php_pkgs: 
      - php
      - php-fpm
      - php-mysqlnd
    db_pkg: mariadb105-server
    web_service: nginx
    db_service: mariadb 
    php_service: php-fpm
    web_index_file: /usr/share/nginx/html/index.html
  tasks:
    - name: Install Web Server
      ansible.builtin.yum:
        name: "{{ web_pkg }}"
        state: present
    
    - name: Install PHP packages
      ansible.builtin.yum:
        name: "{{ php_pkgs }}"
        state: present  
    
    - name: Start and enable Web server
      ansible.builtin.systemd:
        name: "{{ web_service }}"
        state: started
        enabled: yes

    - name: Start and enable PHP-FPM
      ansible.builtin.systemd:
        name: "{{ php_service }}"
        state: started
        enabled: yes
    
    - name: Deploy html page on web server
      ansible.builtin.copy:
        dest:   "{{ web_index_file }}"
        content: "<h1> Welcome to 2 tier application setup using Ansible running on {{inventory_hostname}} </h1>"
        owner: nginx
        group: nginx
        mode: '0644'

# DB Server Playbook
- name: Deployment of Database server
  hosts: dbserver
  become: yes

  vars:
    db_pkg: mariadb105-server
    db_service: mariadb 

  tasks:
    - name: Install DB server
      ansible.builtin.yum:
        name: "{{ db_pkg }}"
        state: present

    - name: Start and enable DB server
      ansible.builtin.systemd:
        name: "{{ db_service }}"
        state: started
        enabled: yes
        
    - name: Create a sample database
      ansible.builtin.shell:
        cmd: mysql -u root -e "CREATE DATABASE ansible_db;"